name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4', ]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild build-for-testing -project Algorithms.xcodeproj -scheme Algorithms -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4'
        env:
          destination: ${{ matrix.destination }}
